import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>OpenSea, the largest NFT marketplace</title>
        <meta
          content="A peer-to-peer marketplace for NFTs, rare digital items and crypto collectibles. Buy, sell, auction, and discover CryptoKitties, Decentraland, Gods Unchained cards, blockchain game items, and more. Over 100,000 collectibles on sale now!"
          name="description"
        ></meta>
        <link
          href="/images/32x32.png"
          rel="icon"
          sizes="32x32"
          type="image/png"
        ></link>
        <link href="https://opensea.io/" rel="icon"></link>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
